name: "CI"

permissions: "read-all"

on:
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: "bash"

env:
  FORCE_COLOR: "1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    name: "Test (${{ matrix.python-version }})"
    runs-on: "ubuntu-latest"
    continue-on-error: false

    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b"

    - name: "Setup Python"
      uses: "actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb"
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Run tests"
      run: |
        python -m pip install -r requirements/test.txt
        python -m pip install .
        pytest tests/
